const books = [
  {
    id: 1,
    name: "The Hunger Games ",
    author: "Suzanne Collins",
    price: "$50",
    rating: 4,
    published_year:2010,
    is_favourite: false,
  },
  {
    id: 2,
    name: "Jane Eyre",
    author: " Louisa May Alcott",
    price: "$50",
    rating: 4,
    published_year:2012,
    is_favourite: false,
  },
  {
    id: 11,
    name: "Wuthering Heights",
    author: "George Orwell",
    price: "$50",
    rating: 4,
    published_year:2011,
    is_favourite: false,
  },
  {
    id: 3,
    name: "Animal Farm",
    author: " Homer",
    price: "$50",
    rating: 4,
    published_year:2013,
    is_favourite: false,
  },
  {
    id: 4,
    name: "Memoirs of a Geisha",
    author: "Maurice Sendak",
    price: "$50",
    rating: 4,
    published_year:2018,
    is_favourite: false,
  },
  {
    id: 5,
    name: "To Kill a Mockingbird",
    author: "Alice Sebold",
    price: "$50",
    rating: 4,
    published_year:2012,
    is_favourite: false,
  },
  {
    id: 6,
    name: "Dracula",
    author: " Bram Stoker",
    price: "$50",
    rating: 4,
    published_year:2019,
    is_favourite: false,
  },
  {
    id: 7,
    name: "Green Eggs and Ham",
    author: "Dr. Seuss",
    price: "$50",
    rating: 4,
    published_year:2022,
    is_favourite: false,
  },
  {
    id: 8,
    name: "One Hundred Years of Solitude",
    author: "author1",
    price: "$50",
    rating: 4,
    published_year:2017,
    is_favourite: false,
  },
  {
    id: 9,
    name: "Frankenstein: The 1818 Text",
    author: "author1",
    price: "$50",
    rating: 4,
    published_year:2023,
    is_favourite: false,
  },
];

export default books;
